# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineedu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.AddField(
            model_name='department',
            name='universities',
            field=models.ManyToManyField(related_name='departments', to='onlineedu.University'),
        ),
        migrations.AddField(
            model_name='university',
            name='town',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
