# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineedu', '0002_auto_20170330_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='onlineedu.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pdf', models.CharField(max_length=20)),
                ('word_doc', models.CharField(max_length=20)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_material', to='onlineedu.Course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='onlineedu.CourseMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='course_materials',
            field=models.ManyToManyField(related_name='books', to='onlineedu.CourseMaterial'),
        ),
    ]
