# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineedu', '0003_auto_20170330_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='description', help_text='A brief description of the course'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.CharField(default='path/to/logo', max_length=200),
        ),
    ]
